<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NoStdLib>true</NoStdLib>
    <NoCompilerStandardLib>true</NoCompilerStandardLib>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>7.3</LangVersion>
    <Optimize>true</Optimize>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Cube3D</AssemblyName>
    <RuntimeMetadataVersion>0</RuntimeMetadataVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- ProjectReference resolves corlib regardless of Debug/Release configuration -->
    <ProjectReference Include="..\..\corlib\corlib.csproj" />
  </ItemGroup>

</Project>
